services:
  db:
    image: postgres:15
    container_name: db
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    image: yuressa/bapo-labs1-backend:latest
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  frontend:
    build: ./frontend
    image: yuressa/bapo-labs1-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  db_data:
